<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="/webjars/bootstrap/5.3.2/css/bootstrap.min.css">


    <title>Home</title>
</head>
<body>
<header>

</header>
<form action="/pizza" method="post">
    <select class="form-select" aria-label="Default select example" name="pizza">
        <option selected>Open this select menu</option>
        <option value="0">Маргарита</option>
        <option value="1">Четыре сыра</option>
        <option value="2">Гавайская</option>
    </select>
    <input type="submit" value="Pizza">
</form>
</body>
<script src="/webjars/bootstrap/5.3.2/js/bootstrap.min.js"></script>
</html>